### PR TITLE
Apply prettier config to all files, and migrate to ESLint

### LINKED ISSUE #53: Prettier
Does it conflict with ESLint/TSLint?

### PR DESCRIPTION
**Pull request by lynzrand**
## Related issues/discussions

closes #53 

## Description of the changes

- Add Prettier to project config
- Add ESLint to project config
- Apply Prettier formatter to all files in the project

### CODE REVIEW

**Comment by izgzhen** [comment]
Awesome, will read in a few minutes

**Comment by lynzrand** [comment]
Just added https://github.com/okonet/lint-staged for pre-commit linting & formatting

**Comment by izgzhen** [comment]
Thanks. I noticed that you updated the yarn lock -- which also includes taobao nom registry as upstream. I will probably regenerate another yarn.lock as a checked in version later though.

**Comment by lynzrand** [comment]
Uh-oh, that’s my fault. I’ll be careful next time!

发件人: Zhen Zhang<mailto:notifications@github.com>
发送时间: 2021年3月11日 16:39
收件人: chafan-dev/chafan-frontend<mailto:chafan-frontend@noreply.github.com>
抄送: Rynco Maekawa<mailto:lynzrand@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [chafan-dev/chafan-frontend] Apply prettier config to all files, and migrate to ESLint (#54)


Thanks. I noticed that you updated the yarn lock -- which also includes taobao nom registry as upstream. I will probably regenerate another yarn.lock as a checked in version later though.

―

**Comment by izgzhen** [comment]
I've pushed a new lock file.

**Pull request merged**
